app:
  dev: true
  FrontEnd: "http://frontend.ptflp.ru"

db:
  net: "tcp"
  driver: "mysql"
  dbname: "golight"
  username: "root"
  password: ""
  host: "golightdb"
  timeout: 10

Email:
  ServerAddress: "smtp.mail.ru"
  Port: "465"
  From: ""
  Login: ""
  Password: ""
  SendGrid: ""

SMSC:
  login: ""
  pwd: ""
  cost: "3"
  fmt: "3"
  dev: false

redis:
  host: "golightredis"
  port: 6379

server:
  port: 8955